
CREATE USER elroot WITH
      LOGIN
      CONNECTION LIMIT 1
      PASSWORD 'v4uwf314d5#rt';

CREATE USER ellokal WITH
      NOLOGIN
      CONNECTION LIMIT 30
      PASSWORD '1w5b5ufh';

CREATE DATABASE ellokal
      TEMPLATE template0
      ENCODING 'UTF8'
          CONNECTION LIMIT 30;

REVOKE CONNECT ON DATABASE ellokal FROM PUBLIC;
GRANT ALL PRIVILEGES ON DATABASE ellokal to elroot;
GRANT CONNECT ON DATABASE ellokal TO elroot;

GRANT CONNECT ON DATABASE ellokal TO ellokal;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ellokal;


